name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          request_pty: true
          script_stop: true
          script: |
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                    git config --global --add safe.directory /var/www/html/zoikotelecom-reactNextTypeTail
                    cd /var/www/html/zoikotelecom-reactNextTypeTail && echo "cd OK"
                    git fetch origin && echo "fetch OK"
                    git reset --hard origin/main && echo "reset OK"
                    npm install && echo "install OK"
                    npm run build && echo "build OK"
                    pm2 restart zoikotelecom && echo "pm2 OK"